### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by Aurora273** [Aurora273/Ermakov.Y.V.-Kursovaya#1]
Техническое задание

1. Общие сведения
   Название проекта: Разработка приложения для вязки собак 
   Заказчик проекта: КФ МГТУ им. Н. Э. Баумана
   Разработчик: Студент КФ МГТУ им. Н. Э. Баумана группы ИУК5-51Б Ермаков Я.В
2. Назначение и цели создания (развития) системы:
2.1. Назначение: Разработка приложения для облегчения и улучшения процесса вязки собак, предоставляя информацию о доступных партнерах, их характеристиках и предоставляя инструменты для связи между владельцами собак.
2.2. Цели:
    • Уменьшить время, затрачиваемое на поиск подходящего партнера для вязки, до 15 минут.
    • Увеличить количество успешных вязок на 30% в первые 6 месяцев использования приложения.
    • Предоставить пользователям возможность просматривать детальные профили не менее чем у 90% зарегистрированных партнеров.
3. Характеристика объектов автоматизации:
3.1. Пользовательский интерфейс для регистрации и аутентификации пользователей.
3.2. Профили пользователей с возможностью добавления информации о собаках.
3.3. Фильтры и инструменты поиска партнеров для вязки.
3.4. Чат для коммуникации между пользователями.
3.5. Возможность оценки и оставления отзывов о партнерах.
4. Требования к системе:
Функциональные требования:
4.1.1. Регистрация новых пользователей с обязательной верификацией электронной почты или мобильного номера.
4.1.2. Вход существующих пользователей в систему с использованием учетных данных.
4.1.3. Создание и редактирование профилей пользователей с возможностью добавления информации о собаках.
4.1.4. Функционал поиска партнеров для вязки с фильтрами по параметрам собак.
4.1.5. Возможность отправки запроса на вязку другому пользователю.
4.1.6. Чат для обмена сообщениями между пользователями.
4.1.7. Возможность оставления отзывов и оценок о партнерах.
Нефункциональные требования:
4.2.1. Безопасное хранение и обработка персональных данных пользователей в соответствии с законодательством о защите данных.
4.2.2. Защита от несанкционированного доступа к данным и функционалу приложения.
4.2.3. Отзывчивость интерфейса приложения с задержкой менее Z секунд.
4.2.4. Поддержка не менее N одновременных пользователей в системе.
4.2.5. Поддержка многоязычности с возможностью выбора языка интерфейса.
5. Состав и содержание работ по созданию системы:
5.1. Анализ и проектирование базы данных приложения.
5.2. Разработка пользовательского интерфейса и функционала приложения.
5.3. Разработка серверной части приложения и его интеграция с базой данных.
5.4. Тестирование приложения на соответствие требованиям.
6. Порядок контроля и приемки системы:
	Контроль и приемка будут осуществляться на каждом этапе разработки согласно утвержденному плану контроля и приемки.
7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие:
7.1 Подготовка приложения для вязки собак
8. Требования к документированию:
8.1. Разработка технической документации с описанием архитектуры, интерфейсов и процессов работы приложения.
8.2. Разработка руководства пользователя.
9. Источники разработки:
9.1. Справочная и научная литература по разработке приложений для мобильных устройств.

**Comment by wldmr-key** [comment]
Назначение - для кого предназначено приложение
Цели - с измеримостью все отлично, но кто за это заплатит?
Объекты автоматизации - это то, что существует и без твоего приложения (скорее всего процесс поиска партнера и возникающие при эотм коммуникации), а ты перечисляешь функции приложения

**Comment by Aurora273** [comment]
Назначение: приложение предназначено для заводчиков собак.
На счет кто за это заплатит не совсем понял. Если с точки зрения бизнеса откуда будет прибыль, то в аналогичных приложениях для знакомства людей много вариантов. Как платная подписка для расширения функционала приложения, так и например выведение своего аккаунта в рейтинг по показам профиля( что бы за доп. плату больше людей увидели твой профиль)
Объект автоматизации: 
процесс поиска партнера для вязки
коммуникации возникающие при поиске партнера для вязки

**Comment by wldmr-key** [comment]
>  аналогичных приложениях для знакомства людей много вариантов.

так, выбери какой-нибудь!
