### ISSUE TITLE
Предметная область

### ISSUE THREAD

**Issue by Aurora273** [Aurora273/Ermakov.Y.V.-Kursovaya#4]
Приложение для вязки собак
**Вязка собак** — это процесс размножения собак, при котором мужская собака (кобель) и самка собака партнерятся для производства потомства. Этот процесс может происходить естественным путем, если собаки встречаются и размножаются самостоятельно, или с посредством помощи **заводчика**, который выбирает подходящих партнеров для своих собак с учетом их генетических характеристик, здоровья и породы.
**Заводчик** - это человек или организация, специализирующаяся на разведении и размножении определенной породы собак. Основная цель заводчика - улучшение и сохранение характеристик породы, а также работа над здоровьем, характером и внешностью собак.

Заводчики проводят тщательный отбор родителей для вязки, учитывая их генетические характеристики, здоровье и соответствие стандартам породы. Они также заботятся о качественной реализации и воспитании щенков.

Хороший заводчик следит за здоровьем и благополучием своих собак, предоставляет им достаточно пространства, заботы, кормления и медицинского ухода. Он также обеспечивает социализацию щенков, обучение и поддержку новых владельцев.

Определить породистость собаки а так же наличие прививок и хронических заболеваний может помочь **ветеринарная книжка.**
**Вет. книжка (или вет. паспорт)** - это официальный документ, в котором фиксируется медицинская и иная информация о животном. Этот документ предоставляет владельцу информацию о состоянии здоровья и медицинской истории своего питомца. 

Важно отметить, что хороший заводчик работает в соответствии с этическими стандартами и **стремится к улучшению породы, а не к массовому размножению собак ради прибыли**. Исходя из этого можно сделать вывод что перед заводчиком стоит очень тяжелая задача, выбор особей по строгим критерием которые приведут к улучшению генетических характеристик новорожденных особей.

**Comment by wldmr-key** [comment]
Это очень неплохо пока, но явно не отражает всех аспектов предметной области. В частности, что происходит с деньгами, договоренностя/договорами... С какой информацией оперирует заводчик (без всякого компьютера)? Как?

**Comment by Aurora273** [comment]
Если рассматривать как этот процесс происходит на данный момент без моего приложения, то:

В первую очередь заводчик смотрит наличие вет. книжки, а так же наличие всех необходимых прививок. Далее заводчики договариваются о встрече и происходит внешний осмотр собаки. Важными критериями выбора являются:

- Здоровый вес - нормальный вес показатель здоровья и отсутствия проблем с желудком.

- Поведения - если при прикосновении к собаке она агрессирует  или боится значит у собаки могут быть проблемы с психикой.

- Так же важным критерием является запах из пасти и правильный прикус - это показатель должного ухода и своевременного осмотра у ветеринара.

- Чистые уши - показатель должного ухода.

- Одним из важнейших показателей породистой собаки является клеймо которое находится на ухе либо брюхе.

Как происходит договоренность между заводчиками:

Договор вязки — соглашение сторон (владельцев животных, допущенных в разведение по определенным правилам) о спаривании принадлежащих им собак с целью участия в племенной работе и продажи щенков. По соглашению:

одна сторона (владелец суки) уплачивает второй (хозяину кобеля):

- вознаграждение в натуральном виде (щенок, рожденный от вязки, по первому или второму выбору владельца кобеля – алиментный щенок)

- либо в денежном эквиваленте (средняя стоимость щенка данной породы). Сумма указывается полностью цифрами и прописью.

Договоры РКФ не предусматривался. До 2011 года условия, цена и прочие нюансы прописывались в акте вязки. С 2011 года эти пункты были исключены из формы акта. Это значит, что вопросы расчета и прочие условия, как и решение связанных с ними споров полностью передаются на регулирование хозяев кобеля и суки. При это контроль за исполнением условий РКФ не осуществляет. Все споры, возникшие в ходе решения вязки собак и смежных вопросов, решаются как:

- гражданско-правовой спор путем подачи иска мировому судье (если цена за вязку меньше 50 тысяч рублей);

- в федеральный суд (если цена выше указанной суммы). На Гражданский кодекс РФ есть ссылка непосредственно в Положении [РКФ](https://realpet.ru/uhod/klejmo-u-sobak.html) о племенном разведении.

Официальный образец договора не разработан по настоящее время. Поэтому заводчики могут взять за основу гражданско-правовой договор оказания услуг, поскольку в нем есть разделы о предмете (вязка), условиях исполнения (условия вязки) и вознаграждении (оплата владельцу кобеля). Гражданским кодексом допускается заключать сделки не только по статьям, предусмотренным текстом нормативно-правового акта, но также по разумению договаривающихся сторон, если условия не противоречат закону.

**Comment by wldmr-key** [comment]
вопрос - что из этого ты берешь в систему?
Кстати, твой ответ очень неплох по форме и содержинию и вполне подходит для исследовательской части, даже если у тебя в системе этого нет

**Comment by Aurora273** [comment]
Из того что я написал мне конкретно важно только наличие вет. паспорта, прививок и цвет окраса. Потому что 
это первичные критерии по которым сразу отсеиваются варианты у которых нет вет.паспорта или прививок или не подходящий окрас. А далее уже идут критерии для более детального и тщательного отбора и там без визуального осмотра уже никак. Т.к запах из пасти, поведение, чистоту ушей надо оценивать самому воочию. 
Что касается вопроса денег, то он тоже не играет роли в моей системе, потому что как я написал в предыдущем сообщении цены все договорные и решаются после детального осмотра. Ну и в основном они стандартные потому что берется средняя стоимость щенка на рынке.
