### ISSUE TITLE
Er- Диаграмма и требования к системе

### ISSUE THREAD

**Issue by Aurora273** [Aurora273/Ermakov.Y.V.-Kursovaya#5]
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/39006716-0dfa-4360-abbd-91df98d0bf70)
Сущность user to group нужна для равязки многие ко многим пользователи <N----N> чаты. В них в концептуальной схеме данных будут храниться group_id и user_id  а в чатах будет уже только group_id.

Требования к системе:
4.1.1. Регистрация новых пользователей с обязательной верификацией электронной почты или мобильного номера.
4.1.2. Создание и редактирование профилей пользователей с возможностью добавления информации о собаках.
4.1.3. Возможность отправки запроса на вязку другому пользователю.
4.1.4. Чат для обмена сообщениями между пользователями.
Нефункциональные требования:
4.2.1. Безопасное хранение и обработка персональных данных пользователей в соответствии с законодательством о защите данных.
4.2.2. Защита от несанкционированного доступа к данным и функционалу приложения.

**Comment by wldmr-key** [comment]
Логичнее требования к системе поместить перед концептуальной схемой, так как концептуальная схема следует из описания предметной области и требований к системе

И здесь, конечно, неувязки

В процессе согласования запроса вязки собаки не участвуют? Только заводчики?

Из общих соображений понятно, что суки не всегда готовы к вязке. Это как-нибудь отражается? У меня такое впечатление, что для самых популярных особ чуть ли не график составляется

А фото собачек будет? Что-то не вижу

Нигде в описании не определен запрос на вязку (да ничего не определено, кроме заводчиков и собак)

**Comment by Aurora273** [comment]
Что касается согласования собак, согласен. Выбор лайка/не лайк будет делать человек но от конкретной собаки, поэтому связь будет именно с ними. 
Фото собачек добавил. 
Что касается того что суки не готовы к вязке. Я считаю что в моей системе как только человек находит партнера для вязки, то он просто временно перестает просматривать анкеты других собак за ненадобность. Тогда не произойдет match и не будет переписки. Ограничивать какими то способом из разряда скрытие анкеты или какой то галочки что собака занята я не вижу смысла так как человек просто перестает лайкать других и все. Или опять же может продолжить это делать для того что возможно составить график на будущее. 
Запрос на вязку - это так называемый match. Как он будет работать в системе: 
Заводчик 1 пусть будет Петя зашел в приложение, зарегистрировался и добавил фото своей собаки.
Далее Петя начинает на главной странице лайкать или дизлайкать собак других пользователей. Допустим он лайкнул собаку Заводчика 2 Васи. Происходит запрос на вязку( в реляционной схеме в таблицу запросы на вязки создается строка с id_запроса,id_Собаки_Пети,id_Собаки_Васи, Статус, Дата)
Мы ждем, пока Вася зайдет в приложение и ему попадется фото собаки Пети. Если Вася дизлайкает собаку Пети, то в таблице ставится статус Отклонено и ничего не происходит. Если Васе понравилась собака Пети, то ставится статус принято и происходит match - собаки Васи и Пети понравились друг другу, им открывается переписка.
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/eba5c123-c548-470f-ad63-6668b5a066c7)

**Comment by wldmr-key** [comment]
> им открывается переписка

собакам? ))

Вот это все стоит изложить более инженерным языком в описании предметной области или требованиях. Тема чатов также не раскрыта

**Comment by Aurora273** [comment]
Требования к системе:
4.1.5 Реализовать алгоритм подбора, включая функционал одобрения и отклонения, для пользовательского интерфейса, позволяющего пользователям выражать заинтересованность или неинтерес к потенциальным партнерам на основе предоставленных профилей собак.

**Comment by wldmr-key** [comment]
нужно поразвернутее. Постороннему человеку непонятно. Проверь на ком-нибудь

**Comment by Aurora273** [comment]
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/eb78349b-796d-49fc-b53f-c04f53ca1d2b)


Заводчик пройдя регистрацию и создав анкету собаки попадает на главную страницу. Там он может одобрить или отклонить анкеты собак других заводчик. Для того что бы заводчикам открылся чат, им нужно одобрить анкеты друг друга.
