### ISSUE TITLE
Скетчи интерфейса

### ISSUE THREAD

**Issue by Aurora273** [Aurora273/Ermakov.Y.V.-Kursovaya#6]
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/677384e3-88da-4a05-a52b-0442a22e679f)
![Скетч(профиль](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/9d5b0d99-c60b-4398-8fc0-ba8576ad98f1)
![Скетч(настройки)](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/33d8de7f-c32f-4f2e-aaf2-034c9de277ce)
![Скетч(чаты)](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/5ad54c7e-3e8c-409e-b9b8-05554a1f72e7)

**Comment by wldmr-key** [comment]
картинки милы, но не очень вяжутся с концептуальной схемой

Совет - наполняй скетчи реалистичными картинками и текстами
