### ISSUE TITLE
Анализ аналогов

### ISSUE THREAD

**Issue by Aurora273** [Aurora273/Ermakov.Y.V.-Kursovaya#7]
Я провел анализ прямых конкурентов  и выявил что прямыми конкурентами в сфере вязки являются группы в Соцсетях по подбору партнера для вязки(скриншот 1). Минусом данных групп является то, что их много и они малочисленны по количеству пользователей. Поиск в них не удобен, потому что приходится просматривать анкеты не только собак нужной породы, а все объявления которые там выкладываются(скриншот 2).Так же среди анкет появляются посты с рекламой, что еще больше затягивает поиск необходимого партнера. 
Еще одним конкурентом являются форумы в интернете для подбора партнера для вязки. Этот способ мало чем отличается от групп в соцсетях.
К конкурентам так же можно отнести клубы по подбору собак. Пообщавшись с заводчиком, я узнал что в каждом городе есть собачьи клубы(например как клубы почитателей творчества Пушкина).В данных клубах хозяева собак вместе прививают собак, организуют встречи и массовые мероприятия. Так же в этих клубах можно найти партнеров для вязки. НО эти клубы можно рассматривать не как конкурента , а как будущего партнера, так как очень выгодно будет договориться с управлением клуба о переходе большой группы заводчиков на мою электронную систему подбора.
Изучая форумы и посты в группах, я заметил, что идея о создании приложения у людей зародилась уже давно, но конкретных реализаций до сих пор нет(скриншот 3,4). Пользователи форумов жалуются на очередные опросы от "разработчиков"(скриншот 5) и были бы очень рады воспользоваться таким приложением(скриншот 6,7).
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/95990a47-6bd2-40e4-9691-5a1e072499d5)
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/45ee522a-0122-4542-97b2-9f51a32bc0da)
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/8b1779a6-ce6b-4963-9668-2fbf2f7c0800)
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/c47da1f9-13fa-477f-8d58-8457c20f3a30)
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/cae13777-e346-4e23-820c-06d53a969103)
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/11a96991-2101-4df4-a017-a09047c888d7)
![image](https://github.com/Aurora273/Ermakov.Y.V.-Kursovaya/assets/144378992/232ff2f5-7249-4b7b-b39b-7422f6f48e01)

**Comment by wldmr-key** [comment]
Все супер! Стоит убрать только первое лицо в РПЗ
